apiVersion: v1
kind: Secret
metadata:
  name: telemetrybffsecret
  namespace: staging
type: Opaque
stringData:
  PORT: "8080"
  AUTH0_DOMAIN: 
  REDIS_HOST: "redis-service.staging.svc.cluster.local:6379"
  REDIS_PASSWORD: ""
  USERS_MANAGER_HOST: "users-manager-service.staging.svc.cluster.local:50051"
  DEVICES_MANAGER_HOST: "devices-manager-service.staging.svc.cluster.local:50052"
  TELEMETRY_ANALYSIS_HOST: "telemetry-analysis-service.staging.svc.cluster.local:50053"