# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measures.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emeasures.proto\x12\x06sensor\x1a\x1fgoogle/protobuf/timestamp.proto\",\n\x17MeasuresByDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"0\n\x0bGeolocation\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0b\x63oordinates\x18\x02 \x03(\x01\"n\n\x0eSensorMetadata\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0btype_sensor\x18\x02 \x01(\t\x12\r\n\x05units\x18\x03 \x03(\t\x12%\n\x08location\x18\x04 \x01(\x0b\x32\x13.sensor.Geolocation\"^\n\x06Values\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x10\n\x08humidity\x18\x02 \x01(\x01\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"k\n\x18MeasuresByDeviceResponse\x12\x1e\n\x06values\x18\x01 \x03(\x0b\x32\x0e.sensor.Values\x12/\n\x0fsensor_metadata\x18\x02 \x01(\x0b\x32\x16.sensor.SensorMetadata2g\n\x0bMeasuresIoT\x12X\n\x13GetMeasuresBySensor\x12\x1f.sensor.MeasuresByDeviceRequest\x1a .sensor.MeasuresByDeviceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'measures_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASURESBYDEVICEREQUEST']._serialized_start=59
  _globals['_MEASURESBYDEVICEREQUEST']._serialized_end=103
  _globals['_GEOLOCATION']._serialized_start=105
  _globals['_GEOLOCATION']._serialized_end=153
  _globals['_SENSORMETADATA']._serialized_start=155
  _globals['_SENSORMETADATA']._serialized_end=265
  _globals['_VALUES']._serialized_start=267
  _globals['_VALUES']._serialized_end=361
  _globals['_MEASURESBYDEVICERESPONSE']._serialized_start=363
  _globals['_MEASURESBYDEVICERESPONSE']._serialized_end=470
  _globals['_MEASURESIOT']._serialized_start=472
  _globals['_MEASURESIOT']._serialized_end=575
# @@protoc_insertion_point(module_scope)
