// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/LuisDiazM/backend/users-manager/app"
	"github.com/LuisDiazM/backend/users-manager/domain/users/usecases"
	"github.com/LuisDiazM/backend/users-manager/infraestructure/persistence/mongo"
	"github.com/LuisDiazM/backend/users-manager/infraestructure/persistence/mongo/repositories/users"
	"github.com/LuisDiazM/backend/users-manager/infraestructure/server"
	"github.com/LuisDiazM/backend/users-manager/infraestructure/server/controllers"
)

// Injectors from wire.go:

func CreateApp() *app.Application {
	mongoSettings := app.GetMongoSettings()
	mongoImplementation := mongo.NewMongoImplementation(mongoSettings)
	iUsersDbRepository := users.NewUserDBRepository(mongoImplementation)
	userUsecases := usecases.NewUserUsecases(iUsersDbRepository)
	usersController := controllers.NewUsersController(userUsecases)
	serverGRPCCustom := server.NewServerGRPCCustom(usersController)
	appSettings := app.GetAppSettings()
	application := app.NewApplication(serverGRPCCustom, appSettings)
	return application
}
