// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/LuisDiazM/telemetry-application/backend/devices-manager/app"
	"github.com/LuisDiazM/telemetry-application/backend/devices-manager/infraestructure/messaging"
)

// Injectors from wire.go:

func CreateApp() *app.Application {
	hiveMQSettings := app.GetHiveMQSettings()
	messagingBroker := messaging.NewMessagingBroker(hiveMQSettings)
	appSettings := app.GetAppSettings()
	application := app.NewApplication(messagingBroker, appSettings)
	return application
}
