// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: infraestructure/server/protos/measures/measures.proto

package telemetry_analysis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeasuresIoTClient is the client API for MeasuresIoT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeasuresIoTClient interface {
	GetMeasuresBySensor(ctx context.Context, in *MeasuresByDeviceRequest, opts ...grpc.CallOption) (*MeasuresByDeviceResponse, error)
}

type measuresIoTClient struct {
	cc grpc.ClientConnInterface
}

func NewMeasuresIoTClient(cc grpc.ClientConnInterface) MeasuresIoTClient {
	return &measuresIoTClient{cc}
}

func (c *measuresIoTClient) GetMeasuresBySensor(ctx context.Context, in *MeasuresByDeviceRequest, opts ...grpc.CallOption) (*MeasuresByDeviceResponse, error) {
	out := new(MeasuresByDeviceResponse)
	err := c.cc.Invoke(ctx, "/sensor.MeasuresIoT/GetMeasuresBySensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeasuresIoTServer is the server API for MeasuresIoT service.
// All implementations must embed UnimplementedMeasuresIoTServer
// for forward compatibility
type MeasuresIoTServer interface {
	GetMeasuresBySensor(context.Context, *MeasuresByDeviceRequest) (*MeasuresByDeviceResponse, error)
	mustEmbedUnimplementedMeasuresIoTServer()
}

// UnimplementedMeasuresIoTServer must be embedded to have forward compatible implementations.
type UnimplementedMeasuresIoTServer struct {
}

func (UnimplementedMeasuresIoTServer) GetMeasuresBySensor(context.Context, *MeasuresByDeviceRequest) (*MeasuresByDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeasuresBySensor not implemented")
}
func (UnimplementedMeasuresIoTServer) mustEmbedUnimplementedMeasuresIoTServer() {}

// UnsafeMeasuresIoTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeasuresIoTServer will
// result in compilation errors.
type UnsafeMeasuresIoTServer interface {
	mustEmbedUnimplementedMeasuresIoTServer()
}

func RegisterMeasuresIoTServer(s grpc.ServiceRegistrar, srv MeasuresIoTServer) {
	s.RegisterService(&MeasuresIoT_ServiceDesc, srv)
}

func _MeasuresIoT_GetMeasuresBySensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasuresByDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeasuresIoTServer).GetMeasuresBySensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sensor.MeasuresIoT/GetMeasuresBySensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeasuresIoTServer).GetMeasuresBySensor(ctx, req.(*MeasuresByDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeasuresIoT_ServiceDesc is the grpc.ServiceDesc for MeasuresIoT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeasuresIoT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.MeasuresIoT",
	HandlerType: (*MeasuresIoTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeasuresBySensor",
			Handler:    _MeasuresIoT_GetMeasuresBySensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infraestructure/server/protos/measures/measures.proto",
}
