apiVersion: apps/v1
kind: Deployment
metadata:
  name:  users-manager
  namespace: staging
  labels:
    app:  users-manager
spec:
  selector:
    matchLabels:
      app: users-manager
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  users-manager
    spec:
      containers:
      - name:  users-manager
        image:  luisdiazm/users-manager:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: usersmanagersecret
              key: MONGO_URL
        - name: MONGO_MAXPOOLSIZE
          valueFrom:
            secretKeyRef:
              name: usersmanagersecret
              key: MONGO_MAXPOOLSIZE
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: usersmanagersecret
              key: PORT
        ports:
        - containerPort:  50051
          name:  grpc
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: users-manager-service
  namespace: staging
spec:
  selector:
    app: users-manager
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051