// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/LuisDiazM/backend/telemetry-bff/app"
	"github.com/LuisDiazM/backend/telemetry-bff/infraestructure/web"
)

// Injectors from wire.go:

func CreateApp() *app.Application {
	engine := web.NewHTTPServer()
	settings := app.GetAppSettings()
	application := app.NewApplication(engine, settings)
	return application
}
